name: MLflow CI with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: my_ml_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Verify Conda environment
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Configure Git (safe directory)
        shell: bash -l {0}
        run: |
          git config --global user.email "evameivina@example.com"
          git config --global user.name "Eva Meivina"
          git config --global --add safe.directory '*'

      - name: Run MLflow project
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow run . --env-manager local -P epochs=100 -P batch_size=64

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: evameivina/mlflow:latest
