name: MLflow CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: my_ml_env
          environment-file: MLProject/conda.yaml
          python-version: 3.10
          auto-activate-base: false

      - name: Verify Conda environment
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Configure Git
        run: |
          git config --global user.email "evameivina@example.com"
          git config --global user.name "Eva Meivina"

      - name: Run MLflow project
        shell: bash -l {0}
        run: |
          mlflow run MLProject --env-manager local -P n_estimators=100 -P max_depth=3

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/
